spring:
  application:
    name: app-module

server:
  port: 8082

firebase:
  project-id: proyecto-cparalela
  storage-bucket: proyecto-cparalela.firebasestorage.app

cuda:
  service:
    url: http://filter-service:5000

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/  # ‚Üê Cambiar
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}